// Oxocard.java

import ch.aplu.jgamegrid.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import java.lang.Math.*;

public class Oxocard extends JFrame
{
  private String VERSION = "V 0.92 (March 20, 2018)";

  private class MyMouseAdapter1 implements GGMouseListener
  {
    public boolean mouseEvent(GGMouse mouse)
    {
      jLabel2.setVisible(false);
      jLabel1.setText("       ");
      int x = mouse.getX();
      int y = mouse.getY();
      int r = 80;
      for (int i = 0; i < 8; i++)
      {
        for (int k = 0; k < 8; k++)
        {
          double dx = (coordMatrix[i][k].x - x);
          double dy = (coordMatrix[i][k].y - y);
          if (dx * dx + dy * dy < r)
          {
            GGBackground bg1 = gameGrid1.getBg();
            GGBackground bg2 = gameGrid2.getBg();
            String s = textField2.getText();
            Color color = hexToColor(s);
            if (color == null)
            {
              jLabel1.setText("Illegal color!");
              jPanel7.setBackground(null);
              return false;
            }
            bg1.setPaintColor(color);
            jPanel7.setBackground(color);
            bg1.fillCircle(coordMatrix[i][k], 6);
            Location loc = new Location(k, i);
            bg2.fillCell(loc, color);
            bg2.drawGridLines(Color.GRAY);
            colorMatrix[i][k] = color;
            return false;
          }
        }
      }
      return false;
    }
  }

  private class MyMouseAdapter2 implements GGMouseListener
  {
    public boolean mouseEvent(GGMouse mouse)
    {
      jLabel2.setVisible(false);
      jLabel1.setText("       ");
      int x = mouse.getX();
      int y = mouse.getY();
      Location loc = gameGrid2.toLocationInGrid(x, y);
      GGBackground bg1 = gameGrid1.getBg();
      GGBackground bg2 = gameGrid2.getBg();
      String s = textField2.getText();
      Color color = hexToColor(s);
      if (color == null)
      {
        jLabel1.setText("Illegal color!");
        jPanel7.setBackground(null);
        return false;
      }
      jPanel7.setBackground(color);
      bg1.setPaintColor(color);
      bg1.fillCircle(coordMatrix[loc.y][loc.x], 6);
      bg2.fillCell(loc, color);
      bg2.drawGridLines(Color.GRAY);
      colorMatrix[loc.y][loc.x] = color;
      return false;
    }
  }

  public Oxocard()
  {
    initComponents();
    jLabel1.setText("       ");
    textField2.setText("0xffffff");
    jPanel7.setBackground(Color.WHITE);
    jLabel2.setVisible(false);
    jColorChooser1.setPreviewPanel(new JPanel());
    jRadioButton1.setSelected(false); // Decimal
    jRadioButton2.setSelected(true); // Hex
    jRadioButton5.setSelected(false); // C/C++
    jRadioButton6.setSelected(true); // Python
    gameGrid1.setBgImagePath("sprites/oxocard.gif");
    gameGrid1.setGridColor(new Color(0, 0, 0, 0));
    gameGrid1.setNbHorzCells(12);
    gameGrid1.setNbVertCells(24);
    gameGrid1.setCellSize(20);
    gameGrid1.addMouseListener(new MyMouseAdapter1(), GGMouse.lPress | GGMouse.lDrag);
    gameGrid1.setSimulationPeriod(100);
    gameGrid1.doRun();
    gameGrid2.setNbHorzCells(8);
    gameGrid2.setNbVertCells(8);
    gameGrid2.getBg().drawGridLines(Color.GRAY);
    gameGrid2.addMouseListener(new MyMouseAdapter2(), GGMouse.lPress | GGMouse.lDrag);
    gameGrid2.setSimulationPeriod(100);
    gameGrid2.doRun();
    setTitle("Oxocard Pixel Editor " + VERSION + " [www.aplu.ch]");

    double x0 = 20;
    double y0 = 142.1;
    int x, y;
    GGBackground bg = gameGrid1.getBg();
    bg.setPaintColor(Color.black);
    for (int i = 0; i < 8; i++)
    {
      for (int k = 0; k < 8; k++)
      {
        x = (int)Math.round(x0 + k * 28.1);
        y = (int)Math.round(y0 + i * 28.5);
        Point pt = new Point(x, y);
        bg.fillCircle(pt, 6);
        coordMatrix[i][k] = pt;
        colorMatrix[i][k] = new Color(0, 0, 0);
      }
    }

    jColorChooser1.setColor(Color.WHITE);
    jColorChooser1.getSelectionModel().addChangeListener(new javax.swing.event.ChangeListener()
    {
      @Override
      public void stateChanged(ChangeEvent arg0)
      {
        jLabel2.setVisible(false);
        Color color = jColorChooser1.getColor();
        textField2.setText(String.format("0x%06x", colorToInt(color, 1)));
        jPanel7.setBackground(color);
      }
    });

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel2 = new javax.swing.JPanel();
    gameGrid1 = new ch.aplu.jgamegrid.GameGrid();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jColorChooser1 = new javax.swing.JColorChooser();
    gameGrid2 = new ch.aplu.jgamegrid.GameGrid();
    jPanel1 = new javax.swing.JPanel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jPanel5 = new javax.swing.JPanel();
    jRadioButton5 = new javax.swing.JRadioButton();
    jRadioButton6 = new javax.swing.JRadioButton();
    jPanel6 = new javax.swing.JPanel();
    textField1 = new java.awt.TextField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    textField2 = new java.awt.TextField();
    jLabel1 = new javax.swing.JLabel();
    jPanel7 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    gameGrid1.setGridColor(new java.awt.Color(0, 80, 0));
    gameGrid1.setNbVertCells(12);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(gameGrid1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(gameGrid1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Color Matrix"));

    jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextArea1.setBackground(new java.awt.Color(204, 255, 255));
    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
    jTextArea1.setRows(5);
    jTextArea1.setDisabledTextColor(new java.awt.Color(102, 102, 255));
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    gameGrid2.setGridColor(new java.awt.Color(0, 80, 0));
    gameGrid2.setNbVertCells(12);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Format"));

    jRadioButton1.setText("Decimal");
    jRadioButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jRadioButton1ActionPerformed(evt);
      }
    });

    jRadioButton2.setText("Hex");
    jRadioButton2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jRadioButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(jRadioButton2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jRadioButton1)
          .addComponent(jRadioButton2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Language"));

    jRadioButton5.setText("C/C++");
    jRadioButton5.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jRadioButton5ActionPerformed(evt);
      }
    });

    jRadioButton6.setText("Python");
    jRadioButton6.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jRadioButton6ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jRadioButton6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(24, 24, 24))
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jRadioButton5)
          .addComponent(jRadioButton6))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Reduction Factor (1..50)"));

    textField1.setText("10");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(100, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jButton1.setText("Create Matrix");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Show Matrix");
    jButton2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton2ActionPerformed(evt);
      }
    });

    jLabel2.setText("Bad matrix format!");

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Color"));

    textField2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
    textField2.setText("0xffffff");
    textField2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        textField2ActionPerformed(evt);
      }
    });

    jLabel1.setText("Illegal color!");

    jPanel7.setBackground(new java.awt.Color(255, 51, 153));
    jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 61, Short.MAX_VALUE)
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 19, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(gameGrid2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton1))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7))))
              .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jColorChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(gameGrid2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jButton2)
                  .addComponent(jButton1)
                  .addComponent(jLabel2)))
              .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void textField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textField2ActionPerformed
  {//GEN-HEADEREND:event_textField2ActionPerformed
        jLabel2.setVisible(false);
  }//GEN-LAST:event_textField2ActionPerformed

  private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
  {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
    jLabel2.setVisible(false);
    if (!jRadioButton1.isSelected())
      jRadioButton1.setSelected(true);
    else
    {
      jRadioButton2.setSelected(false);
      matrixFormat = "dec";
    }
  }//GEN-LAST:event_jRadioButton1ActionPerformed

  private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton2ActionPerformed
  {//GEN-HEADEREND:event_jRadioButton2ActionPerformed
    jLabel2.setVisible(false);
    if (!jRadioButton2.isSelected())
      jRadioButton2.setSelected(true);
    else
    {
      jRadioButton1.setSelected(false);
      matrixFormat = "hex";
    }

  }//GEN-LAST:event_jRadioButton2ActionPerformed

  private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton5ActionPerformed
  {//GEN-HEADEREND:event_jRadioButton5ActionPerformed
    jLabel2.setVisible(false);
    if (!jRadioButton5.isSelected())
      jRadioButton5.setSelected(true);
    else
    {
      jRadioButton6.setSelected(false);
      language = "c/c++";
    }
  }//GEN-LAST:event_jRadioButton5ActionPerformed

  private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton6ActionPerformed
  {//GEN-HEADEREND:event_jRadioButton6ActionPerformed
   jLabel2.setVisible(false);
   if (!jRadioButton6.isSelected())
      jRadioButton6.setSelected(true);
    else
    {
      jRadioButton5.setSelected(false);
      language = "python";
    }
  }//GEN-LAST:event_jRadioButton6ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
  {//GEN-HEADEREND:event_jButton1ActionPerformed
   jLabel2.setVisible(false);
   if (language.equals("python"))
      jTextArea1.setText(matrixToTextPython());
    else  // c/c++
      jTextArea1.setText(matrixToTextC());
    jTextArea1.requestFocusInWindow();
    jTextArea1.selectAll();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
  {//GEN-HEADEREND:event_jButton2ActionPerformed
    jLabel2.setVisible(false);
    showMatrix();
  }//GEN-LAST:event_jButton2ActionPerformed

  private void showMatrix()
  {
    try
    {
      String m = jTextArea1.getText().trim();
      if (language.equals("python"))
      {
        if (m.contains("{"))
          throw new Exception();
        String javaMatrix = m.replace('(', '{');
        javaMatrix = javaMatrix.replace(')', '}');
        javaMatrix = javaMatrix.substring(javaMatrix.indexOf('=') + 1);
        showJavaMatrix(javaMatrix);
      }
      else // C/C++
      {
        String javaMatrix = m.substring(m.indexOf('=') + 1);
        showJavaMatrix(javaMatrix);
      }
    }
    catch (Exception ex)
    {
      jLabel2.setVisible(true);
    }
  }

  private void showJavaMatrix(String m)
  {
    String[] lines = m.split("}");
    for (int i = 0; i < 8; i++)
    {
      String line = lines[i].replace("{", "").replace("\n", "").replace("\r", "");
      if (i == 0)
        line = ',' + line;
      String[] items = line.split(",");
      for (int k = 0; k < 8; k++)
      {
        int colorInt = Integer.decode(items[k + 1].trim());
        int d = getReductionFactor();
        Color color = intToColor(colorInt, d);
        colorMatrix[i][k] = color;
      }
    }
    repaintMatrix();
  }

  void repaintMatrix()
  {
    GGBackground bg1 = gameGrid1.getBg();
    GGBackground bg2 = gameGrid2.getBg();
    for (int i = 0; i < 8; i++)
    {
      for (int k = 0; k < 8; k++)
      {
        Color color = colorMatrix[i][k];
        bg1.setPaintColor(color);
        bg1.fillCircle(coordMatrix[i][k], 6);
        Location loc = new Location(k, i);
        bg2.fillCell(loc, color);
      }
    }
    bg2.drawGridLines(Color.GRAY);
  }

  private int getReductionFactor()
  {
    String s = textField1.getText();
    int d = 10;
    try
    {
      d = Integer.parseInt(s);
    }
    catch (NumberFormatException ex)
    {
      textField1.setText("10");
    }
    if (d < 1 || d > 50)
    {
      d = 10;
      textField1.setText("10");
    }
    return d;
  }

  private String matrixToTextPython()
  {
    int d = getReductionFactor();
    String s = "matrix = (\n";
    for (int i = 0; i < 8; i++)
    {
      s += "(";
      for (int k = 0; k < 8; k++)
      {
        if (matrixFormat.equals("hex"))
          s += String.format("0x%06x", colorToInt(colorMatrix[i][k], d));
        else // dec
          s += Integer.toString(colorToInt(colorMatrix[i][k], d));
        if (k < 7)
          s += ",";
      }
      s += ")";
      if (i < 7)
        s += ",\n";
    }
    s += ")\n";
    return s;
  }

  private String matrixToTextC()
  {
    int d = getReductionFactor();
    String s = "int matrix[8][8] = {\n";
    for (int i = 0; i < 8; i++)
    {
      s += "{";
      for (int k = 0; k < 8; k++)
      {
        if (matrixFormat.equals("hex"))
          s += String.format("0x%06x", colorToInt(colorMatrix[i][k], d));
        else // dec
          s += Integer.toString(colorToInt(colorMatrix[i][k], d));
        if (k < 7)
          s += ",";
      }
      s += "}";
      if (i < 7)
        s += ",\n";
    }
    s += "};\n";
    return s;
  }

  private Color hexToColor(String hex)
  {
    int colorInt = 0;
    try
    {
      colorInt = Integer.decode(hex);
    }
    catch (NumberFormatException ex)
    {
      return null;
    }
    return new Color(colorInt);
  }

  private int colorToInt(Color color, int divider)
  {
    int r = color.getRed() / divider;
    int g = color.getGreen() / divider;
    int b = color.getBlue() / divider;
    int a = 0;
    return new Color(r, g, b, a).getRGB();
  }

  private Color intToColor(int colorInt, int divider)
  {
    int b = (colorInt & 0xFF) * divider;
    b = Math.min(255, b);
    int g = ((colorInt >> 8) & 0xFF) * divider;
    g = Math.min(255, g);
    int r = ((colorInt >> 16) & 0xFF) * divider;
    r = Math.min(255, r);
    int a = 255;
    return new Color(r, g, b, a);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new Oxocard().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private ch.aplu.jgamegrid.GameGrid gameGrid1;
  private ch.aplu.jgamegrid.GameGrid gameGrid2;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JColorChooser jColorChooser1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JRadioButton jRadioButton5;
  private javax.swing.JRadioButton jRadioButton6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  private java.awt.TextField textField1;
  private java.awt.TextField textField2;
  // End of variables declaration//GEN-END:variables
  private Point[][] coordMatrix = new Point[8][8];
  private Color[][] colorMatrix = new Color[8][8];
  private String matrixFormat = "hex";
  private String language = "python";

}
